[phases.setup]
nixPkgs = ["python311", "gcc", "libsndfile"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[start]
cmd = "python -m uvicorn app.main:asgi_app --host 0.0.0.0 --port $PORT"
